# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef78759dc1c076e64c20b38fbb0d574bfee28858fb4dded10930ad258400e5737e932ccbe0d0105f47db82391d43ccbc32165f87972cbc6d8990b4d2b6ed4736

test:
  secret_key_base: 556b722fc2469a1372232379858b0930e4cea557fbb8622e32b8e54370871b99331ce67249b843992ca07b2d37a84388affc2220e95fbcc69cd35835a25d5b6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
